suspicious_words = [
    "urgent",
    "click",
    "password",
    "prize",
    "winner",
    "verify",
    "account",
    "payment",
    "pix",

    "urgente",
    "clique",
    "senha",
    "prêmio",
    "ganhador",
    "vencedor",
    "verifique",
    "verificação",
    "conta",
    "pagamento",
    "boleto",
    "cobrança",
    "transferência",
    "depósito",
    "dinheiro",
    "gratuito",
    "grátis",
    "oferta",
    "promoção",
    "desconto",
    "sorteio",
    "premiação",
    "benefício",
    "recompensa",
    "presente",
    "ganhe",
    "ganhou",
    "ganhar",
    "receba",
    "receber",
    "resgate",
    "resgatar",
    "confirme",
    "confirmar",
    "confirmação",
    "acesso",
    "bloqueado",
    "bloqueio",
    "desbloquear",
    "segurança",
    "seguro",
    "security",
    "secure",
    "verification",
    "confirm",
    "access",
    "blocked",
    "unlock",
    "login",
    "signin",
    "sign-in",
    "credential",
    "credentials",
    "code",
    "codigo",
    "código",
    "token",
    "otp",
    "authentication",
    "autenticação",
    "identidade",
    "identity",
    "documento",
    "document",
    "cpf",
    "cartão",
    "card",
    "credit",
    "crédito",
    "debit",
    "débito",
    "bank",
    "banco",
    "banking",
    "invoice",
    "fatura",
    "bill",
    "taxa",
    "fee",
    "refund",
    "reembolso",
    "refund",
    "delivery",
    "entrega",
    "encomenda",
    "pedido",
    "order",
    "tracking",
    "rastreamento",
    "link",
    "website",
    "download",
    "attachment",
    "anexo",
    "suspicious",

    "act now",
    "click here",
    "limited time",
    "last chance",
    "final notice",
    "security alert",
    "account suspended",
    "account expired",
    "reset your password",
    "verify your identity",
    "gift card",
    "wire transfer",
    "social security",
    "pay now",
    "malware",
    "virus",
    "ação imediata",
    "clique aqui",
    "tempo limitado",
    "última chance",
    "aviso final",
    "alerta de segurança",
    "conta suspensa",
    "conta expirada",
    "redefina sua senha",
    "verifique sua identidade",
    "cartão-presente",
    "transferência bancária",
    "pague agora",
    "vírus",
    "malware"
]